var firstName = 'Manon';
console.log(typeof firstName);
console.log("First name is: "+ firstName);
var companyName ="BNY Mellon";
console.log(typeof companyName);
console.log("Company name is: "+ companyName);
var mobileNumber = 8754473368;
console.log(typeof mobileNumber);
console.log("Mobile number is: "+ mobileNumber);
var isAutomation = true;
console.log(typeof isAutomation);
console.log("Is Automation: "+ isAutomation);
var hasPlaywright;
console.log(typeof hasPlaywright);
console.log("Has Playwrigh: "+hasPlaywright);